### ISSUE TITLE
Tor + use_capybara not anonymous

### ISSUE THREAD

**Issue by Oxyless** [joshweir/scraypa#1]
Hey,

Thanks for your amazing lib.
The following configuration seems to ignore the Tor use:

Scraypa.configure do |config|
  config.tor = true

  config.use_capybara = true
  config.driver = :poltergeist
  config.driver_options = {
    :phantomjs => Phantomjs.path,
    :js_errors => false,
    :phantomjs_options => ["--web-security=true"]
  }
end

When I watch my nginx logs with this configuration I see the real IP, not the Tor one (without the use_capybara I see a Tor IP).

Have a good day !

**Comment by joshweir** [comment]
Appreciate the feedback and finding this issue, thanks @Oxyless. 

I suspect that you may need some additional `:phantomjs_options`, see in my [feature test](https://github.com/joshweir/scraypa/blob/c4b1028b94435551ff03f440da6f0d34a842c803/spec/scraypa/shared_examples/tor.rb#L22) I include these settings:
 
    :phantomjs_options => ["--web-security=false", "--ignore-ssl-errors=yes",
                                     "--ssl-protocol=any", "--proxy-type=socks5",
                                     "--proxy=127.0.0.1:9050"]

I think what's most important is that you set the `--proxy-type=socks5` and `--proxy=127.0.0.1:9050` where `127.0.0.1:9050` is your Tor proxy socket. Let me know if you still have issue i'll look into that.
